"""
Фасад клавиатур администратора.
"""
from .admin_misc import *
from .admin_servers import *
from .admin_payments import *
from .admin_tariffs import *
from .admin_groups import *
from .admin_broadcast import *
from .admin_users import *
from .admin_settings import *
from .admin_yadreno import *

__all__ = [
    'BROADCAST_FILTERS',
    'USERS_FILTERS',
    'back_button',
    'home_button',
    'cancel_button',
    'cancel_kb',
    'back_and_home_kb',
    'home_only_kb',
    'admin_main_menu_kb',
    'author_support_kb',
    'admin_logs_menu_kb',
    'stop_bot_confirm_kb',
    'bot_settings_kb',
    'bot_mode_toggle_confirm_kb',
    'force_overwrite_confirm_kb',
    'update_confirm_kb',
    'servers_list_kb',
    'server_view_kb',
    'server_groups_kb',
    'add_server_step_kb',
    'add_server_confirm_kb',
    'add_server_test_failed_kb',
    'edit_server_kb',
    'confirm_delete_kb',
    'payments_menu_kb',
    'crypto_setup_kb',
    'crypto_setup_confirm_kb',
    'cards_management_kb',
    'wata_management_kb',
    'platega_management_kb',
    'cardlink_management_kb',
    'edit_crypto_kb',
    'crypto_management_kb',
    'tariffs_list_kb',
    'tariff_view_kb',
    'add_tariff_step_kb',
    'add_tariff_confirm_kb',
    'edit_tariff_kb',
    'groups_list_kb',
    'group_view_kb',
    'group_delete_confirm_kb',
    'group_select_kb',
    'broadcast_main_kb',
    'broadcast_confirm_kb',
    'broadcast_notifications_kb',
    'broadcast_back_kb',
    'broadcast_notify_back_kb',
    'users_menu_kb',
    'users_list_kb',
    'user_view_kb',
    'user_ban_confirm_kb',
    'key_view_kb',
    'add_key_server_kb',
    'add_key_inbound_kb',
    'add_key_step_kb',
    'add_key_confirm_kb',
    'users_input_cancel_kb',
    'key_action_cancel_kb',
    'key_delete_confirm_kb',
    'sync_deleted_menu_kb',
    'sync_deleted_panel_confirm_kb',
    'sync_deleted_db_confirm_kb',
    'trial_settings_kb',
    'trial_tariff_select_kb',
    'trial_edit_text_cancel_kb',
    'referral_main_kb',
    'referral_level_kb',
    'referral_back_kb',
    'yadreno_admin_no_key_kb',
    'yadreno_admin_chat_kb',
    'yadreno_admin_agent_kb',
    'yadreno_admin_cancel_key_kb',
]
